/* Import of the main stylesheet generated by the SCSS files and the preprocessor */
import '../sass/main.css';

/* Import of the useLocation hook which will enable to get the state passed via the Link components in
* the Header component */
import { useLocation } from 'react-router-dom';

/* Definition of the DisplayGitLabUsers component */
export const DisplayGitLabUsers = () => {

    /* Creation of an instance of useLocation */
    const location = useLocation();
    /* Storing the state data from the useLocation instance */
    const data = location.state.gitLabUserArray;

    console.log(data);

    return(
        <div>
            <h2 className="mb-4">
                React Send / Get State using Link Component Example
            </h2>
            <p>Login: {data[0].username}</p>
        </div>
    )
}