/* Import of main stylesheet generated by the SCSS files and preprocessor*/
import '../sass/main.css';
/* Import of axios client to make API call to backend */
import axios from "axios";
/* Import of React Hooks used in this component */
import { useEffect, useState } from "react";
import { useLocation } from 'react-router-dom';

/* Definition of the GitLabCommits component that displays all commits for a specific repo. The commits are in
* descending order so the latest commit will appear at the top of the list */
export const GitLabCommits = () => {
    /* Declaration and initialisation of the state variable needed in this component */
    const [commitsList, setCommitsList] = useState([]);

    /* Use of the useLocation hook to get the state attribute data from the Link component to this page */
    const location = useLocation();
    const repoId = location.state.repoId;

    /* The useEffect hook to make the axios call to the backend only when the user or repo ID changes */
    useEffect(() => {

        /* The axios call to the gitlabCommits route on the backend. The repo ID name is encoded in
        * the body of the post request */
        axios.post('http://localhost:8000/githubCommits', {
            repoId: repoId
        })
            .then(response => {
                setCommitsList(response.data)
            })
            .catch(error => {
                console.log('Error', error.message);
            })

    }, [repoId]); // useEffect dependency

    return (
        <div>
            {/* Using the Array.map method to loop through the list of commits received back from the backend
             and render the required properties */}
            {commitsList.map((commit, index) => {
                return (
                    <div key={index}>
                        <p>Date: {commit.comitted_date} <span>Comment: {commit.title}</span></p>
                    </div>
                )
            })}
        </div>
    )
}