/* Import of main stylesheet generated by SCSS files and preprocessor */
import '../sass/main.css';

/* The home component. This is the page that will greet the user at the base url */
export const Home = () => {
    return (
        <main className={'home-container'}>
            <section className={'home-content'}>
                <h2 className={'home-heading'}>Version Control System Interface Application</h2>
                <p className={'home-paragraph1'}>
                    This application interfaces with GitHub and GitLab to enable you to search for repositories.
                </p>
                <p className={'home-paragraph2'}>
                    You will be given user and repository details for the selected repository.
                </p>
                <p className={'home-paragraph3'}>
                    We hope you have fun exploring the two VCS providers with this application
                </p>
            </section>
        </main>
    )
}