
import { Routes, Route } from 'react-router-dom';


/* Import of the components needed in this one */
import {Header} from "./components/Header";
import {Home} from "./components/Home";
import {Error} from "./components/Error";
import {DisplayGitHubUsers} from "./components/DisplayGitHubUsers";
import {DisplayGitLabUsers} from "./components/DisplayGitLabUsers";
import {GitHubRepos} from "./components/GitHubRepos";
import {GitHubCommits} from "./components/GitHubCommits";
import {GitLabRepos} from "./components/GitLabRepos";
// import {GitLabCommits} from "./components/GitLabCommits";

/* The main style sheet generated by the SCSS files and preprocessor */
import './sass/main.css';
/* Additional style sheet to render the background because SASS could not resolve the path of the image */
import './app.css';



/* The main component that will ultimately house all other components that are rendered. Weather this
* is directly or indirectly */
export const App = () => {
    return (
        <main className="App">
            <section>
                <Header/>
            </section>
            <Routes>
                <Route path={'/'} element={<Home/>} exact/>
                <Route path={'/displayGitHubUsers'} element={<DisplayGitHubUsers/>}/>
                <Route path={'/displayGitLabUsers'} element={<DisplayGitLabUsers/>}/>
                <Route path={'/githubRepos'} element={<GitHubRepos/>} />
                <Route path={'/gitHubCommits'} element={<GitHubCommits/>}/>
                <Route path={'/gitlabRepos'} element={<GitLabRepos/>}/>
                {/*<Route path={'/gitLabCommits'} element={<GitLabCommits/>}/>*/}
                <Route path={'*'} element={<Error/>} />
            </Routes>
        </main>
    );
}